CREATE SEQUENCE REPORT_BOARD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE TABLE REPORT_BOARD (
    REPORT_ID NUMBER(19) NOT NULL,
    AUTHOR_ID NUMBER(19) NOT NULL,
    REPORT_DATE DATE NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE REPORT_BOARD
ADD CONSTRAINT PK_REPORT_BOARD
PRIMARY KEY (REPORT_ID);

ALTER TABLE REPORT_BOARD
ADD CONSTRAINT FK_REPORT_BOARD_AUTHOR
FOREIGN KEY (AUTHOR_ID)
REFERENCES APP_USERS (USER_ID);

CREATE INDEX IDX_REPORT_DATE_CREATED
ON REPORT_BOARD (
    REPORT_DATE DESC,
    CREATED_AT DESC,
    REPORT_ID DESC
);

CREATE INDEX IDX_REPORT_AUTHOR
ON REPORT_BOARD (AUTHOR_ID);