CREATE SEQUENCE APP_USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    NOCYCLE;

CREATE TABLE APP_USERS (
    USER_ID NUMBER(19) NOT NULL,
    USERNAME VARCHAR2(50 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) NOT NULL,
    ROLE VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE APP_USERS
ADD CONSTRAINT PK_APP_USERS
PRIMARY KEY (USER_ID);

ALTER TABLE APP_USERS
ADD CONSTRAINT UK_APP_USERS_USERNAME
UNIQUE (USERNAME);

ALTER TABLE APP_USERS
ADD CONSTRAINT UK_APP_USERS_EMAIL
UNIQUE (EMAIL);

ALTER TABLE APP_USERS
ADD CONSTRAINT CK_APP_USERS_ROLE
CHECK (ROLE IN ('USER', 'ADMIN'));

ALTER TABLE APP_USERS
ADD CONSTRAINT CK_APP_USERS_ENABLED
CHECK (ENABLED IN (0, 1));