-- 1) 게시글 번호 발급용 시퀀스
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOMAXVALUE
NOCACHE
NOCYCLE;


-- 2) 게시판 테이블
CREATE TABLE BOARD (
    BOARD_ID NUMBER(19) NOT NULL,
    AUTHOR_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    CONTENT CLOB NOT NULL,
    IS_NOTICE NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);


-- 3) 기본키
ALTER TABLE BOARD
ADD CONSTRAINT PK_BOARD
PRIMARY KEY (BOARD_ID);


-- 4) 작성자 외래키
ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_AUTHOR
FOREIGN KEY (AUTHOR_ID)
REFERENCES APP_USERS (USER_ID);


-- 5) 공지 여부 값 제한
ALTER TABLE BOARD
ADD CONSTRAINT CK_BOARD_NOTICE
CHECK (IS_NOTICE IN (0, 1));


-- 6) 공지 우선 + 최신순 조회 인덱스
CREATE INDEX IDX_BOARD_NOTICE_CREATED
ON BOARD (IS_NOTICE DESC, CREATED_AT DESC, BOARD_ID DESC);


-- 7) 작성자별 조회 및 권한 확인 인덱스
CREATE INDEX IDX_BOARD_AUTHOR
ON BOARD (AUTHOR_ID);