-- Oracle 21c / XE용 사용자 테이블 생성 스크립트
-- factoryview 계정으로 접속한 뒤 한 번 실행하세요.
-- Oracle의 USER는 예약된 식별자/함수이므로 테이블명은 APP_USERS를 사용합니다.

CREATE SEQUENCE APP_USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE APP_USERS (
    USER_ID       NUMBER(19)      NOT NULL,
    USERNAME      VARCHAR2(50)    NOT NULL,
    PASSWORD_HASH VARCHAR2(255)   NOT NULL,
    DISPLAY_NAME  VARCHAR2(100)   NOT NULL,
    EMAIL         VARCHAR2(255)   NOT NULL,
    ROLE          VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    ENABLED       NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_APP_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UK_APP_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_APP_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_APP_USERS_ROLE CHECK (ROLE IN ('USER', 'ADMIN')),
    CONSTRAINT CK_APP_USERS_ENABLED CHECK (ENABLED IN (0, 1))
);

CREATE INDEX IX_APP_USERS_ENABLED ON APP_USERS (ENABLED);

COMMENT ON TABLE APP_USERS IS 'MES 웹서비스 사용자 계정';
COMMENT ON COLUMN APP_USERS.PASSWORD_HASH IS 'Spring Security PasswordEncoder 해시값';
COMMENT ON COLUMN APP_USERS.DISPLAY_NAME IS '로그인 후 화면에 표시할 사용자 이름';
COMMENT ON COLUMN APP_USERS.ENABLED IS '1: 사용 가능, 0: 사용 중지';

COMMIT;
