-- ============================================================
-- MES 생산 모니터링 - 게시판 최종 스키마
-- Database : Oracle 21c XE
-- User     : FACTORYVIEW
-- Tool     : DBeaver
--
-- 사전 조건: APP_USERS 테이블과 APP_USERS_SEQ가 먼저 생성되어 있어야 합니다.
-- 실행 방법: FACTORYVIEW 계정에서 전체 파일을 Execute SQL Script로 실행
-- macOS Option+X / Windows Alt+X
-- ============================================================

-- 0. 현재 접속 계정 확인 (FACTORYVIEW여야 함)
SELECT USER AS CURRENT_DATABASE_USER
FROM DUAL;

-- 1. 게시글 PK 발급용 시퀀스
CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCACHE
    NOCYCLE;

-- 2. 게시판 테이블
CREATE TABLE BOARD (
    BOARD_ID    NUMBER(19)                         NOT NULL,
    AUTHOR_ID   NUMBER(19)                         NOT NULL,
    TITLE       VARCHAR2(200 CHAR)                 NOT NULL,
    CONTENT     CLOB                               NOT NULL,
    IS_NOTICE   NUMBER(1) DEFAULT 0                NOT NULL,
    CREATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP  NOT NULL,
    UPDATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP  NOT NULL,

    CONSTRAINT PK_BOARD
        PRIMARY KEY (BOARD_ID),

    CONSTRAINT FK_BOARD_AUTHOR
        FOREIGN KEY (AUTHOR_ID)
        REFERENCES APP_USERS (USER_ID),

    CONSTRAINT CK_BOARD_NOTICE
        CHECK (IS_NOTICE IN (0, 1))
);

-- 3. 공지 우선 + 최신순 조회용 인덱스
CREATE INDEX IDX_BOARD_NOTICE_CREATED
    ON BOARD (IS_NOTICE DESC, CREATED_AT DESC, BOARD_ID DESC);

-- 4. 작성자별 조회 및 외래키 처리용 인덱스
CREATE INDEX IDX_BOARD_AUTHOR
    ON BOARD (AUTHOR_ID);

-- 5. 설명
COMMENT ON TABLE BOARD IS 'MES 생산 모니터링 게시판';
COMMENT ON COLUMN BOARD.BOARD_ID IS '게시글 PK';
COMMENT ON COLUMN BOARD.AUTHOR_ID IS '작성자 APP_USERS.USER_ID';
COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.IS_NOTICE IS '공지 여부: 1 공지, 0 일반';
COMMENT ON COLUMN BOARD.CREATED_AT IS '작성 일시';
COMMENT ON COLUMN BOARD.UPDATED_AT IS '수정 일시';

-- 6. 생성 확인
SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'BOARD',
    'BOARD_SEQ',
    'IDX_BOARD_NOTICE_CREATED',
    'IDX_BOARD_AUTHOR'
)
ORDER BY OBJECT_TYPE, OBJECT_NAME;

-- 7. 컬럼 확인
SELECT
    COLUMN_ID,
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'BOARD'
ORDER BY COLUMN_ID;
