-- ============================================================
-- MES 보고서 게시판 REPORT_BOARD 최종 생성 SQL
-- 기능: 보고 기준일 + 구조화 내용(문단/표)
-- Database : Oracle 21c XE
-- User     : FACTORYVIEW
-- Tool     : DBeaver
--
-- 새 데이터베이스에서만 사용하세요.
-- 이미 REPORT_BOARD가 있다면 04_migrate_report_board_date_table.sql을 사용합니다.
-- 각 SQL 문장 안에 커서를 놓고 한 문장씩 실행하세요.
-- macOS: Command + Enter / Windows: Ctrl + Enter
-- ============================================================

SELECT USER AS CURRENT_DATABASE_USER
FROM DUAL;

SELECT COLUMN_NAME
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'APP_USERS'
  AND COLUMN_NAME = 'USER_ID';

CREATE SEQUENCE REPORT_BOARD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE TABLE REPORT_BOARD (
    REPORT_ID NUMBER(19) NOT NULL,
    AUTHOR_ID NUMBER(19) NOT NULL,
    REPORT_DATE DATE NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE REPORT_BOARD
ADD CONSTRAINT PK_REPORT_BOARD
PRIMARY KEY (REPORT_ID);

ALTER TABLE REPORT_BOARD
ADD CONSTRAINT FK_REPORT_BOARD_AUTHOR
FOREIGN KEY (AUTHOR_ID)
REFERENCES APP_USERS (USER_ID);

CREATE INDEX IDX_REPORT_DATE_CREATED
ON REPORT_BOARD (REPORT_DATE DESC, CREATED_AT DESC, REPORT_ID DESC);

CREATE INDEX IDX_REPORT_AUTHOR
ON REPORT_BOARD (AUTHOR_ID);

COMMENT ON TABLE REPORT_BOARD IS 'MES 보고서 게시판';
COMMENT ON COLUMN REPORT_BOARD.REPORT_ID IS '보고서 PK';
COMMENT ON COLUMN REPORT_BOARD.AUTHOR_ID IS '작성자 APP_USERS.USER_ID';
COMMENT ON COLUMN REPORT_BOARD.REPORT_DATE IS '보고 기준일';
COMMENT ON COLUMN REPORT_BOARD.TITLE IS '보고서 제목';
COMMENT ON COLUMN REPORT_BOARD.CONTENT IS '보고서 문단 및 표 구조를 저장하는 JSON 또는 기존 일반 텍스트';
COMMENT ON COLUMN REPORT_BOARD.CREATED_AT IS '작성 일시';
COMMENT ON COLUMN REPORT_BOARD.UPDATED_AT IS '수정 일시';

SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'REPORT_BOARD',
    'REPORT_BOARD_SEQ',
    'IDX_REPORT_DATE_CREATED',
    'IDX_REPORT_AUTHOR'
)
ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'REPORT_BOARD'
ORDER BY COLUMN_ID;
