-- ============================================================
-- 기존 REPORT_BOARD 마이그레이션
-- 변경: REPORT_DATE 추가, 공지 기능 제거, 날짜 정렬 인덱스 생성
-- 기존 보고서 내용과 작성자 정보는 유지됩니다.
--
-- 반드시 FACTORYVIEW 계정에서 각 문장을 한 문장씩 실행하세요.
-- macOS: Command + Enter / Windows: Ctrl + Enter
-- ============================================================

SELECT USER AS CURRENT_DATABASE_USER
FROM DUAL;

-- 1) 보고 기준일 컬럼을 우선 NULL 허용으로 추가
ALTER TABLE REPORT_BOARD
ADD REPORT_DATE DATE;

-- 2) 기존 데이터는 작성일의 날짜를 보고 기준일로 지정
UPDATE REPORT_BOARD
SET REPORT_DATE = TRUNC(CAST(CREATED_AT AS DATE))
WHERE REPORT_DATE IS NULL;

COMMIT;

-- 3) 보고 기준일을 필수로 변경
ALTER TABLE REPORT_BOARD
MODIFY REPORT_DATE NOT NULL;

-- 4) 기존 공지 정렬 인덱스 제거
DROP INDEX IDX_REPORT_NOTICE_CREATED;

-- 5) 기존 공지 CHECK 제약조건 제거
ALTER TABLE REPORT_BOARD
DROP CONSTRAINT CK_REPORT_BOARD_NOTICE;

-- 6) 공지 컬럼 제거
ALTER TABLE REPORT_BOARD
DROP COLUMN IS_NOTICE;

-- 7) 보고 기준일 최신순 인덱스 생성
CREATE INDEX IDX_REPORT_DATE_CREATED
ON REPORT_BOARD (REPORT_DATE DESC, CREATED_AT DESC, REPORT_ID DESC);

-- 8) 설명 추가
COMMENT ON COLUMN REPORT_BOARD.REPORT_DATE IS '보고 기준일';
COMMENT ON COLUMN REPORT_BOARD.CONTENT IS '보고서 문단 및 표 구조를 저장하는 JSON 또는 기존 일반 텍스트';

-- 9) 결과 확인
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'REPORT_BOARD'
ORDER BY COLUMN_ID;

SELECT INDEX_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'REPORT_BOARD'
ORDER BY INDEX_NAME;
