spring.application.name=backend
server.port=8080
spring.output.ansi.enabled=always

# Oracle DB
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=factoryview
spring.datasource.password=2449
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false